FROM apache/airflow:2.9.3-python3.10

# Install additional Python packages
# add --no-cache-dir if there is problem 

COPY requirements.txt .
RUN pip install --default-timeout=1000  -r requirements.txt

# Copy DAG files

