# Dockerfile.main-spark


FROM bitnami/spark:3.5.0


WORKDIR /opt/bitnami/spark/jobs


COPY requirements.txt .
USER root
RUN chmod +x requirements.txt


RUN pip install -r requirements.txt


USER 1001