FROM apache/superset:4.0.2

USER root

RUN pip install pyhive	

ENV ADMIN_USERNAME $ADMIN_USERNAME
ENV ADMIN_EMAIL $ADMIN_EMAIL
ENV ADMIN_PASSWORD $ADMIN_PASSWORD

COPY ./superset/superset-init.sh /superset-init.sh

RUN chmod +x /superset-init.sh

COPY ./superset/superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

USER root
ENTRYPOINT [ "/superset-init.sh" ]
USER superset