# Use the Presto base image
FROM prestodb/presto:0.289

# Copy the configuration files into the container
COPY ./presto_config_files/config.properties /opt/presto-server/etc/config.properties
COPY ./presto_config_files/jvm.config /opt/presto-server/etc/jvm.config

# adding cassandra connector 
RUN mkdir -p /opt/presto-server/etc/catalog
COPY ./presto_config_files/cassandra.properties /opt/presto-server/etc/catalog/cassandra.properties



# Start Presto server
CMD ["launcher", "start"]



